[package]
name = "eww_utils_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
eww_utils = { version = "0.1.0", path = "../eww_utils" }

[[bin]]
name = "eww-utils"
path = "src/main.rs"
